[package]
name = "gitbook2text-rs"
version = "0.1.0-alpha"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["fs", "rt", "rt-multi-thread", "macros"] }
futures = "0.3.31"
reqwest = "0.12.23"
pulldown-cmark = "0.13.0"
